version: '3.8'

services:
  quiz-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DB=quizdb
      - MYSQL_PORT=3306
    depends_on:
      - mysql
    networks:
      - quiz-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quizdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quiz-network

volumes:
  mysql_data:

networks:
  quiz-network:
    driver: bridge